### ISSUE TITLE
Shapefile Reading Error

### ISSUE THREAD

**Issue by MrZombie69232** [GeospatialPython/pyshp#197]
Syntax :- **sf = shapefile.Reader("Users\Mr Zombie\Desktop\SortedRDR_0N1N_58E59E\837.shp")**
Traceback (most recent call last):

  Error I am getting :-
```
_File "<ipython-input-12-e3bcb35a9a96>", line 1, in <module>
    sf = shapefile.Reader("Users\Mr Zombie\Desktop\SortedRDR_0N1N_58E59E\837.shp")

  File "C:\Users\Public\Anaconda3\lib\site-packages\shapefile.py", line 553, in __init__
    self.load(args[0])

  File "C:\Users\Public\Anaconda3\lib\site-packages\shapefile.py", line 646, in load
    raise ShapefileException("Unable to open %s.dbf or %s.shp." % (shapeName, shapeName))

ShapefileException: Unable to open Users\Mr Zombie\Desktop\SortedRDR_0N1N_58E59E\837.dbf or Users\Mr Zombie\Desktop\SortedRDR_0N1N_58E59E\837.shp._
```

**Comment by yudi941210** [comment]
file path can't find ,you need check true file path

**Comment by MrZombie69232** [comment]
Thanks! It was due to space in my username ...Thanks!!
