### ISSUE TITLE
UnicodeDecodeError on some shapefiles

### ISSUE THREAD

**Issue by michelspeiser** [GeospatialPython/pyshp#200]
When trying to read some shapefiles 
(for example this one: http://healthsites.io/api/v2/facilities/shapefile/Japan/download )

the following error occurs when going through the shapeRecords:

```
Traceback (most recent call last):                                             
  File "healthsites-fetch.py", line 30, in <module>                            
    for i, r in enumerate(reader.shapeRecords()):                              
  File "/Users/ms/shapes-fetch/.venv/lib/python3.7/site-packages/shapefile.py", line 1039, in shapeRecords
    for rec in zip(self.shapes(), self.records())])                            
  File "/Users/ms/shapes-fetch/.venv/lib/python3.7/site-packages/shapefile.py", line 1012, in records
    r = self.__record(oid=i)                                                   
  File "/Users/ms/shapes-fetch/.venv/lib/python3.7/site-packages/shapefile.py", line 987, in __record
    value = u(value, self.encoding, self.encodingErrors)                       
  File "/Users/ms/shapes-fetch/.venv/lib/python3.7/site-packages/shapefile.py", line 104, in u
    return v.decode(encoding, encodingErrors)                                  
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe5 in position 99: unexpected end of data
```

**Comment by hlg** [comment]
Most likely your records contain string encoded not in Unicode. I have experienced the same with a dataset with street names encoded in iso-8859-1.

If you know the encoding, you can pass it to the reader like this:

    sf = shapefile.Reader("latin1.dbf", encoding = "latin1")

If you don't know it, you can suppress the error by passing the error handling option to use by the Unicode decoder, e.g. 

    sf = shapefile.Reader("latin1.dbf", encodingError="ignore")

Other options are  `"replace"` or `"backslashreplace"`, see the [Python Unicode Howto](https://docs.python.org/3/howto/unicode.html) for details.

**Comment by karimbahgat** [comment]
Thanks @hlg !
