### ISSUE TITLE
check if polygon is closed fails

### ISSUE THREAD

**Issue by Nikolaus** [GeospatialPython/pyshp#261]
### PyShp Version

2.3.1

### Python Version

3.10.7

### Your code

```shell
with shp.Writer(path[:-4]+'_offset.shp', shapefile.POLYGON) as writer:
        writer.field('name', 'C')
        writer.poly([points.T])
        writer.record('polygon1')
```

### Full stacktrace

```shell
Traceback (most recent call last):
  File "/home/horn/develop/antelope/zamg_antelope/scripts/./shapeoffset.py", line 154, in <module>
    main()
  File "/home/horn/develop/antelope/zamg_antelope/scripts/./shapeoffset.py", line 150, in main
    save_offset(args.path, offseted)
  File "/home/horn/develop/antelope/zamg_antelope/scripts/./shapeoffset.py", line 118, in save_offset
    writer.poly([points.T])
  File "/opt/antelope/python3.10.7/lib/python3.10/site-packages/shapefile.py", line 2464, in poly
    self._shapeparts(parts=polys, shapeType=shapeType)
  File "/opt/antelope/python3.10.7/lib/python3.10/site-packages/shapefile.py", line 2524, in _shapeparts
    if part[0] != part[-1]:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

### Other notes

Obviously, the problem here is comparing two array with multiple elements. A dumb would be to compare all elements like here:

for part in parts:
                # if part[0] != part[-1]:
                append = False
                for ndx in range(len/part[0])):
                   if part[0][ndx] != part[-1][ndx]:
                      append = True
                   if append:
                      part.append(part[0])

**Comment by JamesParrott** [comment]
What was the value of `points.T` Nikolaus?  

I've reproduced this (Python 3.11.4, Windows 11, x86, numpy==1.26.0, pyshp==2.3.1):

```
import numpy as np
import shapefile as shp

def f(convert = None, file_name = 'test_polygon_bug_261.shp'):

    points = [[0,0], [1,0],[1,1]]
    
    if convert is not None:
        points = [convert(point) for point in points]

    with shp.Writer(file_name, shp.POLYGON) as w:
        w.field('name', 'C')
        w.poly([points])
        w.record('triangle')
        
f()

f(convert = np.array)
```

Equality and inequality on numpy arrays is evaluated element wise, the error in _shapeparts in:

```
if part[0] != part[-1]:
```

comes when numpy.array.__bool__ is called on an array of length 2 or more, e.g.:

```
>>> l = [0,0]

>>> np.array(l) == np.array(l)
array([ True,  True])

>>> assert np.array(l) == np.array(l)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```
