### ISSUE TITLE
Python 2.7 UnicodeEncodeError when to save chinese in records

### ISSUE THREAD

**Issue by caesar0301** [GeospatialPython/pyshp#30]
I am writing some csv data into a shapefile of POINT type. One of the csv fields is in chinese and the pyshp.Writer complains about the encoding failure. Any ideas?

```
Traceback (most recent call last):
  File "apmap2shapefile.py", line 31, in write2shp
    shpw.save(outfile)
  File "/usr/local/lib/python2.7/site-packages/pyshp-1.2.3-py2.7.egg/shapefile.py", line 1061, in save
    self.saveDbf(target)
  File "/usr/local/lib/python2.7/site-packages/pyshp-1.2.3-py2.7.egg/shapefile.py", line 1033, in saveDbf
    self.__dbfRecords()
  File "/usr/local/lib/python2.7/site-packages/pyshp-1.2.3-py2.7.egg/shapefile.py", line 916, in __dbfRecords
    value = str(value)[:size].ljust(size)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)
```

**Comment by karimbahgat** [comment]
House-cleaning: All encoding-related issues and PRs have been collected in and can be referenced from #74.
